# Generated by Django 2.1 on 2018-10-01 12:14

from django.db import migrations


def populate_gas_types(apps, schema_editor):
    GasType = apps.get_model('leads', 'GasType')
    for i in ['Gasolina', 'Diesel', 'Híbrido', 'Eléctrico', 'H2', 'LPG', 'CNG', 'LNG']:
        GasType.objects.create(name=i)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_gas_types),
    ]
