# Generated by Django 2.1 on 2018-10-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20181002_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='note',
        ),
        migrations.AddField(
            model_name='lead',
            name='note',
            field=models.ManyToManyField(blank=True, to='leads.Note'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='note',
        ),
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.ManyToManyField(blank=True, to='leads.Note'),
        ),
    ]
