# Generated by Django 2.1 on 2018-10-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20181002_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_task_date',
            field=models.DateTimeField(blank=True, help_text='Keep first task date to do. Needed for making date filters on leads grid', null=True),
        ),
    ]
