# Generated by Django 2.1 on 2018-11-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20181127_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='result',
            field=models.CharField(blank=True, choices=[('not_available', 'No disponible'), ('negative', 'Negative'), ('reserved_vehicle', 'Vehicle reserved'), ('unreachable', 'Unreachable'), ('wrong', 'Wrong')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('date', 'Citation'), ('appraisal', 'Appraisal'), ('budget', 'Budget'), ('financing', 'Financing'), ('warranty', 'Warranty'), ('vehicle_information', 'Vehicle information'), ('response_information_mail', 'Respuesta con información mediante mail'), ('pending_assignment', 'Pendiente de asignación'), ('other', 'Otros')], max_length=255),
        ),
    ]
