# Generated by Django 2.1 on 2018-12-12 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_auto_20181211_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='concession_email',
            field=models.EmailField(blank=True, help_text='Email de concesión', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='concession_phone',
            field=models.CharField(blank=True, help_text='Phone', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
