# Generated by Django 2.1 on 2019-02-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_origin_available_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionaire',
            name='notes',
            field=models.ManyToManyField(blank=True, to='leads.Note'),
        ),
    ]
