# Generated by Django 2.1 on 2019-02-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_concessionaire_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_click2call',
            field=models.BooleanField(default=False, help_text='Set True when tasks is created with button Click2Call'),
        ),
    ]
