# Generated by Django 2.1 on 2019-04-08 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_task_id_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionaire',
            name='concession_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de la casa oficial de la concesión'),
        ),
        migrations.AlterField(
            model_name='concessionaire',
            name='mask_c2c',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mascara [src] a mostrar como llamante'),
        ),
    ]
