# Generated by Django 2.1 on 2019-04-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_historicalclient_historicallead_historicalrequest_historicaltask'),
        ('leads', '0026_auto_20190408_1325'),
    ]

    operations = [
    ]
