# Generated by Django 2.1 on 2019-04-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_merge_20190416_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='id_call',
            field=models.FloatField(blank=True, help_text='ID único de la llamada', null=True),
        ),
    ]
