# Generated by Django 2.1 on 2019-06-14 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0030_auto_20190425_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLeadAction',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('lead_status_planing', models.CharField(choices=[('commercial_management', 'Commercial management'), ('tracing', 'Tracing')], help_text='Estado esperado en la próxima actuación', max_length=255)),
                ('date', models.DateTimeField(help_text='Fecha de planificación de actuación')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Alerta'), ('immediate', 'Urgente')], help_text='Estado de urgencia de la actuación', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_lead', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.HistoricalLead')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.Lead')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Actividad del lead',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LeadAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('lead_status_planing', models.CharField(choices=[('commercial_management', 'Commercial management'), ('tracing', 'Tracing')], help_text='Estado esperado en la próxima actuación', max_length=255)),
                ('date', models.DateTimeField(help_text='Fecha de planificación de actuación')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Alerta'), ('immediate', 'Urgente')], help_text='Estado de urgencia de la actuación', max_length=255)),
                ('history_lead', models.ForeignKey(editable=False, help_text='Captura la copia de la instancia en el instante de creación', on_delete=django.db.models.deletion.CASCADE, to='leads.HistoricalLead')),
                ('history_tasks', models.ManyToManyField(blank=True, to='leads.HistoricalTask')),
                ('lead', models.ForeignKey(help_text='Lead asociado', on_delete=django.db.models.deletion.CASCADE, to='leads.Lead')),
                ('user', models.ForeignKey(help_text='Usuario que ha realizado la planificación de la actividad', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad del lead',
                'verbose_name_plural': 'Actividades del lead',
            },
        ),
    ]
