# Generated by Django 2.1 on 2019-06-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_historicalleadaction_leadaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalleadaction',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('warning', 'Alerta'), ('immediate', 'Urgente'), ('done', 'Realizada')], help_text='Estado de urgencia de la actuación', max_length=255),
        ),
        migrations.AlterField(
            model_name='leadaction',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('warning', 'Alerta'), ('immediate', 'Urgente'), ('done', 'Realizada')], help_text='Estado de urgencia de la actuación', max_length=255),
        ),
    ]
