# Generated by Django 2.1 on 2019-07-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0036_auto_20190627_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='type',
            field=models.CharField(choices=[('date', 'Visita / Test Drive'), ('appraisal', 'Appraisal'), ('budget', 'Budget'), ('financing', 'Financing'), ('warranty', 'Warranty'), ('vehicle_information', 'Vehicle information'), ('response_information_mail', 'Respuesta a solicitud vía Email'), ('pending_assignment', 'Pendiente de asignación'), ('lost_call', 'Atender una llamada perdida'), ('other', 'Otros')], max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('date', 'Visita / Test Drive'), ('appraisal', 'Appraisal'), ('budget', 'Budget'), ('financing', 'Financing'), ('warranty', 'Warranty'), ('vehicle_information', 'Vehicle information'), ('response_information_mail', 'Respuesta a solicitud vía Email'), ('pending_assignment', 'Pendiente de asignación'), ('lost_call', 'Atender una llamada perdida'), ('other', 'Otros')], max_length=255),
        ),
    ]
