# Generated by Django 2.1 on 2019-11-11 09:30

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0040_auto_20191111_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='attended_date',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='is_attended', null=True, when={True}),
        ),
        migrations.AlterField(
            model_name='lead',
            name='attended_date',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='is_attended', null=True, when={True}),
        ),
    ]
