# Generated by Django 2.1 on 2019-11-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0041_auto_20191111_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallead',
            name='attended_date',
        ),
        migrations.RemoveField(
            model_name='historicallead',
            name='is_attended',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='attended_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_attended',
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='status',
            field=models.CharField(choices=[('new', 'new opportunity'), ('attended', 'Attended'), ('pending', 'Pending'), ('commercial_management', 'Commercial management'), ('tracing', 'Tracing'), ('end', 'End')], default='new', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'new opportunity'), ('attended', 'Attended'), ('pending', 'Pending'), ('commercial_management', 'Commercial management'), ('tracing', 'Tracing'), ('end', 'End')], default='new', max_length=255),
        ),
    ]
