# Generated by Django 2.1 on 2019-11-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0044_auto_20191125_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='computed_call_asa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='computed_email_asa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='status_call',
            field=models.CharField(blank=True, choices=[('undefined', 'Desconocido'), ('attended', 'Atendida'), ('not_attended', 'No atendida'), ('out_of_working_hours', 'Fuera de horario laboral')], max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='computed_call_asa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='computed_email_asa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status_call',
            field=models.CharField(blank=True, choices=[('undefined', 'Desconocido'), ('attended', 'Atendida'), ('not_attended', 'No atendida'), ('out_of_working_hours', 'Fuera de horario laboral')], max_length=224, null=True),
        ),
    ]
