# Generated by Django 2.1 on 2020-04-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0054_auto_20200423_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallead',
            old_name='requests_notes',
            new_name='request_notes',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='requests_notes',
            new_name='request_notes',
        ),
    ]
