# Generated by Django 2.1 on 2020-04-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0059_auto_20200429_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='result_reason',
            field=models.CharField(blank=True, choices=[('rechaza_financiacion', 'Rechaza financiación'), ('rechaza_tasacion', 'Rechaza tasación'), ('rechaza_precio', 'Rechaza precio'), ('aplaza_compra', 'Aplaza compra'), ('compra_competencia', 'Compra competencia'), ('pre-reservado', 'Pre-Reservado'), ('reservado', 'Reservado'), ('publicidad', 'Publicidad'), ('otro_departamento', 'Otro Departamento'), ('error', 'Error')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='result_reason',
            field=models.CharField(blank=True, choices=[('rechaza_financiacion', 'Rechaza financiación'), ('rechaza_tasacion', 'Rechaza tasación'), ('rechaza_precio', 'Rechaza precio'), ('aplaza_compra', 'Aplaza compra'), ('compra_competencia', 'Compra competencia'), ('pre-reservado', 'Pre-Reservado'), ('reservado', 'Reservado'), ('publicidad', 'Publicidad'), ('otro_departamento', 'Otro Departamento'), ('error', 'Error')], max_length=255, null=True),
        ),
    ]
