# Generated by Django 2.1 on 2020-05-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0062_auto_20200505_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmanagement',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
