# Generated by Django 2.2 on 2020-05-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0066_leadmanagement_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadmanagement',
            name='datetime',
        ),
    ]
