# Generated by Django 2.2 on 2020-07-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0070_auto_20200702_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='comercial_category',
            field=models.CharField(blank=True, choices=[('new', 'Nuevo'), ('km0', 'Km0'), ('seminew', 'Seminuevo'), ('used', 'Ocasión')], max_length=255),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='power',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('new', 'Nuevo'), ('km0', 'Km0'), ('seminew', 'Seminuevo'), ('used', 'Ocasión')], max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='comercial_category',
            field=models.CharField(blank=True, choices=[('new', 'Nuevo'), ('km0', 'Km0'), ('seminew', 'Seminuevo'), ('used', 'Ocasión')], max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='power',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('new', 'Nuevo'), ('km0', 'Km0'), ('seminew', 'Seminuevo'), ('used', 'Ocasión')], max_length=255),
        ),
    ]
