# Generated by Django 2.2 on 2020-07-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0073_auto_20200702_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='request_type',
            field=models.CharField(blank=True, choices=[('new', 'Nuevo'), ('used', 'Ocasión'), ('km0', 'Kilometro 0'), ('management', 'Gerencia'), ('seminew', 'Seminuevo'), ('apv', 'Postventa'), ('acc', 'Accesorios')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='request_type',
            field=models.CharField(blank=True, choices=[('new', 'Nuevo'), ('used', 'Ocasión'), ('km0', 'Kilometro 0'), ('management', 'Gerencia'), ('seminew', 'Seminuevo'), ('apv', 'Postventa'), ('acc', 'Accesorios')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='comercial_category',
            field=models.CharField(blank=True, choices=[('request_product', 'Producto solicitado'), ('offered_product', 'Producto ofertado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='comercial_category',
            field=models.CharField(blank=True, choices=[('request_product', 'Producto solicitado'), ('offered_product', 'Producto ofertado')], max_length=255),
        ),
    ]
