# Generated by Django 2.2 on 2020-07-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0083_auto_20200729_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='comercial_category',
            field=models.CharField(blank=True, choices=[('request_product', 'Producto solicitado'), ('offered_product', 'Producto ofertado')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='comercial_category',
            field=models.CharField(blank=True, choices=[('request_product', 'Producto solicitado'), ('offered_product', 'Producto ofertado')], max_length=255, null=True),
        ),
    ]
