# Generated by Django 2.2 on 2020-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0084_auto_20200729_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='ad_link',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ad_link',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
