# Generated by Django 2.2 on 2020-08-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0086_leadmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionaire',
            name='hubspot_api_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Api Key para HubSpot'),
        ),
        migrations.AddField(
            model_name='concessionaire',
            name='hubspot_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ID de concesionario en HubSpot'),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='hubspot_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='hubspot_status',
            field=models.BooleanField(default=False),
        ),
    ]
