# Generated by Django 2.2 on 2020-08-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0092_merge_20200827_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleversion',
            name='gas_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.GasType'),
        ),
        migrations.AlterField(
            model_name='businessactivity',
            name='custom_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='custom_id',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
