# Generated by Django 2.2 on 2020-08-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0093_auto_20200828_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
