# Generated by Django 2.2 on 2020-09-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0095_auto_20200828_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.Sector'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='sector',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.Sector'),
        ),
    ]
