# Generated by Django 2.2 on 2020-09-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0100_auto_20200904_1153'),
        ('leads', '0100_auto_20200904_1036'),
    ]

    operations = [
    ]
