# Generated by Django 2.2 on 2020-10-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source_channels', '0004_auto_20201026_1800'),
        ('leads', '0101_merge_20200909_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='channel2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='source_channels.Channel'),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='origin2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.Origin'),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='psa_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='channel2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='source_channels.Channel'),
        ),
        migrations.AddField(
            model_name='lead',
            name='origin2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.Origin'),
        ),
        migrations.AddField(
            model_name='lead',
            name='psa_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='result_reason',
            field=models.CharField(blank=True, choices=[('rechaza_financiacion', 'Rechaza financiación'), ('rechaza_tasacion', 'Rechaza tasación'), ('rechaza_precio', 'Rechaza precio'), ('aplaza_compra', 'Aplaza compra'), ('compra_competencia', 'Compra competencia'), ('compra_competencia_precio', 'Compra competencia por precio'), ('compra_competencia_proximidad', 'Compra competencia por proximidad'), ('compra_competencia_stock', 'Compra competencia por stock'), ('infinanciable', 'Infinanciable'), ('aplaza_decision', 'Aplaza decisión'), ('otro', 'Otro'), ('duplicado', 'Duplicado'), ('cita_cancelada', 'Cita cancelada'), ('informacion_cliente_incorrecta', 'Información cliente incorrecta'), ('ilocalizable', 'Ilocalizable'), ('disconforme_tasacion', 'Disconforme con tasación'), ('caducado', 'Caducado'), ('no_encaja_producto', 'No le encaja el producto'), ('no_encaja_precio', 'No le encaja el precio'), ('no_encaja_cuota', 'No le encaja la cuota'), ('vehiculo_ya_vendido', 'Vehiculo ya vendido'), ('pre-reservado', 'Pre-Reservado'), ('reservado', 'Reservado'), ('publicidad', 'Publicidad'), ('otro_departamento', 'Otro Departamento'), ('error', 'Error'), ('pedido', 'Pedido'), ('reservado', 'Reservado')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='result_reason',
            field=models.CharField(blank=True, choices=[('rechaza_financiacion', 'Rechaza financiación'), ('rechaza_tasacion', 'Rechaza tasación'), ('rechaza_precio', 'Rechaza precio'), ('aplaza_compra', 'Aplaza compra'), ('compra_competencia', 'Compra competencia'), ('compra_competencia_precio', 'Compra competencia por precio'), ('compra_competencia_proximidad', 'Compra competencia por proximidad'), ('compra_competencia_stock', 'Compra competencia por stock'), ('infinanciable', 'Infinanciable'), ('aplaza_decision', 'Aplaza decisión'), ('otro', 'Otro'), ('duplicado', 'Duplicado'), ('cita_cancelada', 'Cita cancelada'), ('informacion_cliente_incorrecta', 'Información cliente incorrecta'), ('ilocalizable', 'Ilocalizable'), ('disconforme_tasacion', 'Disconforme con tasación'), ('caducado', 'Caducado'), ('no_encaja_producto', 'No le encaja el producto'), ('no_encaja_precio', 'No le encaja el precio'), ('no_encaja_cuota', 'No le encaja la cuota'), ('vehiculo_ya_vendido', 'Vehiculo ya vendido'), ('pre-reservado', 'Pre-Reservado'), ('reservado', 'Reservado'), ('publicidad', 'Publicidad'), ('otro_departamento', 'Otro Departamento'), ('error', 'Error'), ('pedido', 'Pedido'), ('reservado', 'Reservado')], max_length=255, null=True),
        ),
    ]
