# Generated by Django 2.2 on 2020-11-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0105_auto_20201027_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalleadaction',
            name='lead_status_planing',
            field=models.CharField(choices=[('new', 'Nuevo'), ('commercial_management', 'Commercial management'), ('tracing', 'Tracing'), ('attended', 'Attended'), ('end', 'Closed')], help_text='Estado esperado en la próxima actuación', max_length=255),
        ),
        migrations.AlterField(
            model_name='leadaction',
            name='lead_status_planing',
            field=models.CharField(choices=[('new', 'Nuevo'), ('commercial_management', 'Commercial management'), ('tracing', 'Tracing'), ('attended', 'Attended'), ('end', 'Closed')], help_text='Estado esperado en la próxima actuación', max_length=255),
        ),
    ]
