# Generated by Django 2.2 on 2020-12-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0107_auto_20201120_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmanagement',
            name='event',
            field=models.CharField(blank=True, choices=[('lead_not_attended', 'Lead no atendido'), ('lead_attended', 'Lead atendido'), ('lead_end', 'Lead finalizado'), ('lead_reactivated', 'Lead reactivado'), ('lead_create_task', 'Nueva tarea creada en lead'), ('lead_done_task', 'Tarea finalizada en lead'), ('lead_create_traking', 'Nuevo seguimiento en lead'), ('lead_done_traking', 'Seguimiento finalizado en lead'), ('incoming_all', 'Llamada entrante en lead'), ('outcomming_all', 'Llamada saliente en lead'), ('outcomming_all', 'WhatsApp enviado'), ('change_user', 'Cambio de asignacion')], max_length=224, null=True),
        ),
    ]
