# Generated by Django 2.2 on 2022-03-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0112_auto_20220308_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fleet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='fleet2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='segment',
            field=models.CharField(choices=[('tur', 'Turismo'), ('comercial', 'Comercial'), ('moto', 'Motocicleta'), ('other', 'Otro')], default='other', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='fleet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='fleet2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='segment',
            field=models.CharField(choices=[('tur', 'Turismo'), ('comercial', 'Comercial'), ('moto', 'Motocicleta'), ('other', 'Otro')], default='other', max_length=255),
        ),
    ]
