# Generated by Django 2.2 on 2022-03-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0113_auto_20220308_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='finalcial_km_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='financial_term',
            field=models.IntegerField(choices=[(3, '3'), (6, '6'), (9, '9'), (12, '12'), (15, '15'), (18, '18'), (21, '21'), (24, '24'), (27, '27'), (30, '30'), (33, '33'), (36, '36'), (39, '39'), (42, '42'), (45, '45'), (48, '48'), (51, '51'), (54, '54'), (57, '57'), (60, '60'), (63, '63'), (66, '66'), (69, '69'), (72, '72'), (75, '75'), (78, '78'), (81, '81'), (84, '84'), (87, '87'), (90, '90'), (93, '93'), (96, '96'), (99, '99'), (102, '102'), (105, '105'), (108, '108'), (111, '111'), (114, '114'), (117, '117'), (120, '120')], null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='initial_payment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='maximum_monthlyfee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='number_vehicles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='oportunity_state',
            field=models.IntegerField(choices=[(0, 'LOST'), (1, 'WON')], null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='percent_comision',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='pff',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='price_discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='purchase_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='purchase_method',
            field=models.CharField(choices=[('count', 'CONTADO'), ('rent', 'RENTING'), ('lease', 'LEASING'), ('fin', 'FINANCIACION')], default='count', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='rejection_reason',
            field=models.CharField(choices=[('too_high', 'Price too high'), ('other_dealer', 'Has opted for another dealer'), ('other_brand', 'Has opted for another brand'), ('offer_too_low', 'Trade-in offer too low'), ('moved', 'Moved purchase'), ('cancel', 'Contract cancelled'), ('declined', 'Declined financing'), ('used', 'Used vehicle'), ('no_news', 'No news from client/prospect'), ('lost', 'Lost-Mass Ops')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='segment',
            field=models.CharField(choices=[('tur', 'Turismo'), ('comercial', 'Comercial'), ('moto', 'Motocicleta'), ('other', 'Otro')], default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='total_commision',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='finalcial_km_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='financial_term',
            field=models.IntegerField(choices=[(3, '3'), (6, '6'), (9, '9'), (12, '12'), (15, '15'), (18, '18'), (21, '21'), (24, '24'), (27, '27'), (30, '30'), (33, '33'), (36, '36'), (39, '39'), (42, '42'), (45, '45'), (48, '48'), (51, '51'), (54, '54'), (57, '57'), (60, '60'), (63, '63'), (66, '66'), (69, '69'), (72, '72'), (75, '75'), (78, '78'), (81, '81'), (84, '84'), (87, '87'), (90, '90'), (93, '93'), (96, '96'), (99, '99'), (102, '102'), (105, '105'), (108, '108'), (111, '111'), (114, '114'), (117, '117'), (120, '120')], null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='initial_payment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='maximum_monthlyfee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='number_vehicles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='oportunity_state',
            field=models.IntegerField(choices=[(0, 'LOST'), (1, 'WON')], null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='percent_comision',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pff',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price_discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_method',
            field=models.CharField(choices=[('count', 'CONTADO'), ('rent', 'RENTING'), ('lease', 'LEASING'), ('fin', 'FINANCIACION')], default='count', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rejection_reason',
            field=models.CharField(choices=[('too_high', 'Price too high'), ('other_dealer', 'Has opted for another dealer'), ('other_brand', 'Has opted for another brand'), ('offer_too_low', 'Trade-in offer too low'), ('moved', 'Moved purchase'), ('cancel', 'Contract cancelled'), ('declined', 'Declined financing'), ('used', 'Used vehicle'), ('no_news', 'No news from client/prospect'), ('lost', 'Lost-Mass Ops')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='segment',
            field=models.CharField(choices=[('tur', 'Turismo'), ('comercial', 'Comercial'), ('moto', 'Motocicleta'), ('other', 'Otro')], default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_commision',
            field=models.IntegerField(null=True),
        ),
    ]
