# Generated by Django 2.2 on 2022-03-16 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('source_channels', '0004_auto_20201026_1800'),
        ('leads', '0114_auto_20220309_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='purchase_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('RSPCRM_campaingId', models.CharField(blank=True, max_length=255, null=True)),
                ('RSPCRM_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('campaignType', models.CharField(max_length=255, null=True)),
                ('brandRange', models.CharField(blank=True, max_length=255, null=True)),
                ('distributionBranch', models.CharField(blank=True, max_length=255, null=True)),
                ('startDate', models.DateTimeField(default=None, null=True)),
                ('endDate', models.DateTimeField(default=None, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('goal', models.CharField(blank=True, max_length=255, null=True)),
                ('productName', models.CharField(blank=True, max_length=255, null=True)),
                ('sourceSystem', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('offer', models.IntegerField(default=0)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('communicationType', models.CharField(blank=True, max_length=255, null=True)),
                ('legalEntityPartnerNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('investment', models.IntegerField(default=0)),
                ('utm_campaing', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('concessionaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.Concessionaire')),
                ('note', models.ManyToManyField(blank=True, to='leads.Note')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.Origin')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='source_channels.Source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
