# Generated by Django 2.2 on 2022-03-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0117_remove_campaign_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='expenses',
        ),
        migrations.AddField(
            model_name='campaign',
            name='expenses',
            field=models.TextField(default='[]'),
        ),
    ]
