# Generated by Django 2.2 on 2022-03-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0119_auto_20220317_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='concession_id',
            field=models.IntegerField(null=True),
        ),
    ]
