# Generated by Django 2.2 on 2022-03-17 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0122_auto_20220317_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.VehicleBrand'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.VehicleModel'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.VehicleVersion'),
        ),
    ]
