# Generated by Django 2.2 on 2022-03-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0123_auto_20220317_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='offer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
