# Generated by Django 2.2 on 2022-03-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0125_auto_20220317_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='communicationType',
            field=models.CharField(choices=[('type1', 'Tipo de Comunicación #1'), ('type2', 'Tipo de Comunicación #2'), ('type3', 'Tipo de Comunicación #3')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('on', 'Activo'), ('off', 'Inactivo')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaignType',
            field=models.CharField(choices=[('type1', 'Tipo de Campaña #1'), ('type2', 'Tipo de Campaña #2'), ('type3', 'Tipo de Campaña #3')], max_length=255, null=True),
        ),
    ]
