# Generated by Django 2.2 on 2022-03-17 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source_channels', '0004_auto_20201026_1800'),
        ('leads', '0126_auto_20220317_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='source_channels.Channel'),
        ),
    ]
