# Generated by Django 2.2 on 2022-03-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_channels', '0005_auto_20220317_0747'),
        ('leads', '0127_campaign_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='channel',
        ),
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.ManyToManyField(null=True, to='source_channels.Channel'),
        ),
    ]
