# Generated by Django 2.2 on 2022-03-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0128_auto_20220317_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='channel',
            field=models.ManyToManyField(to='source_channels.Channel'),
        ),
    ]
