# Generated by Django 2.2 on 2022-03-17 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source_channels', '0005_auto_20220317_0747'),
        ('leads', '0129_auto_20220317_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='channel',
        ),
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='source_channels.Channel'),
        ),
    ]
