# Generated by Django 2.2 on 2022-03-17 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0130_auto_20220317_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='leads.Lead'),
        ),
    ]
