# Generated by Django 2.2 on 2022-03-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0134_auto_20220318_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='offer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
