# Generated by Django 2.2 on 2022-03-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0135_auto_20220322_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleversion',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'Manual'), ('MANUAL', 'Manual'), ('automatic', 'Automatico'), ('AUTOMATIC', 'Automatico'), ('AUTOMATICO', 'Automatico')], max_length=64),
        ),
    ]
