# Generated by Django 2.2 on 2022-04-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0136_auto_20220325_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='RSPCRM_origin',
            field=models.CharField(blank=True, choices=[('retail_campaign', 'Retail Campaign'), ('wholesale_car_campaign', 'Wholesale Car Campaign'), ('wholesale_motor_campaign', 'Wholesale Motorcycle Campaign'), ('service_campaign', 'Service Campaign'), ('ext_aftersales_system', 'External Aftersales System')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='brandRange',
            field=models.CharField(blank=True, choices=[('all', 'ALL'), ('bmw_car', 'BMW_CAR'), ('bmwi_car', 'BMWI_CAR'), ('bmw_motor', 'BMW_MOTORCYCLE'), ('mini_car', 'MINI_CAR')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaignType',
            field=models.CharField(blank=True, choices=[('display', 'Display'), ('email', 'Email'), ('banner', 'Internet / Banner'), ('mailing', 'Mailing / Flyer'), ('promo', 'Promotion'), ('radio', 'Radio'), ('tele', 'Telemarketing'), ('event', 'Event'), ('other', 'Other'), ('ads', 'Banner Ads'), ('referral', 'Referral Program'), ('enterprise', 'Enterprise')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='communicationType',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('letter', 'Letter'), ('other', 'Other'), ('messaging_services', 'Messaging Service'), ('sms', 'SMS'), ('in_car', 'In Car')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('postponed_change', 'Postponed - Change of Plan'), ('postponed_not_performed', 'Postponed - Not Performed'), ('aborted', 'Aborted')], max_length=255, null=True),
        ),
    ]
