# Generated by Django 2.2 on 2022-04-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0139_auto_20220424_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='event_type',
            field=models.CharField(blank=True, choices=[('templateMessageSent', 'TemplateMessageSent'), ('message', 'Message')], max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='origin',
            field=models.CharField(blank=True, choices=[('whatsapp', 'Whatsapp'), ('other', 'Otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='wa_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
