# Generated by Django 2.1 on 2019-01-23 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'Week',
                'verbose_name_plural': 'Weeks',
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_hour', models.TimeField(blank=True, null=True)),
                ('end_hour', models.TimeField(blank=True, null=True)),
                ('working_day', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Weekday',
                'verbose_name_plural': 'Weekdays',
            },
        ),
        migrations.AddField(
            model_name='week',
            name='friday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_as_friday', to='work_calendar.Weekday'),
        ),
        migrations.AddField(
            model_name='week',
            name='monday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_as_monday', to='work_calendar.Weekday'),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_as_saturday', to='work_calendar.Weekday'),
        ),
        migrations.AddField(
            model_name='week',
            name='sunday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_as_sunday', to='work_calendar.Weekday'),
        ),
        migrations.AddField(
            model_name='week',
            name='thursday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_as_thursday', to='work_calendar.Weekday'),
        ),
        migrations.AddField(
            model_name='week',
            name='tuesday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_as_tuesday', to='work_calendar.Weekday'),
        ),
        migrations.AddField(
            model_name='week',
            name='wednesday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_as_wednesday', to='work_calendar.Weekday'),
        ),
        migrations.AlterUniqueTogether(
            name='week',
            unique_together={('id', 'friday'), ('id', 'sunday'), ('id', 'monday'), ('id', 'tuesday'), ('id', 'thursday'), ('id', 'wednesday'), ('id', 'saturday')},
        ),
    ]
