# Generated by Django 2.2 on 2020-10-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source_channels', '0003_auto_20190128_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_channel', to='source_channels.Channel'),
        ),
    ]
