# Generated by Django 2.2 on 2022-03-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_channels', '0004_auto_20201026_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(),
        ),
    ]
