# Generated by Django 2.0.1 on 2018-03-14 16:02
import html
from django.db import migrations

def fix_html_entities(apps, schema_editor):
   for country in apps.get_model("countries", "Country").objects.all():
       country.name = html.unescape(country.name)
       country.save()

   for province in apps.get_model("countries", "Province").objects.all():
       province.name = html.unescape(province.name)
       province.save()

   for locality in apps.get_model("countries", "Locality").objects.all():
       locality.name = html.unescape(locality.name)
       locality.save()


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_populate_tables'),
    ]

    operations = [
        migrations.RunPython(fix_html_entities)
    ]
