from django.db import models

from infoauto.leads.models import Concessionaire
from infoauto.users.models import User


class LeadMaster(models.Model):
    id = models.PositiveIntegerField(primary_key=True, db_column="id")
    concesion_nombre = models.CharField(db_column="Nombre de la concesion", max_length=512)
    origen = models.CharField(db_column="Origen", max_length=1024)
    medio = models.CharField(db_column="Medio", max_length=1024)
    origen_publicidad = models.CharField(db_column="Origen publicidad", max_length=1024)
    exposicion = models.BooleanField(db_column="Exposicion")

    asignado = models.CharField(db_column="Asignado a", max_length=1024)
    fecha_llamada_entrante = models.CharField(db_column="Fecha llamada entrante", max_length=1024)
    estado = models.CharField(db_column="Estado", max_length=1024)
    resultado = models.CharField(db_column="Resultado", max_length=1024)
    motivo_resultado = models.CharField(db_column="Motivo resultado", max_length=1024)
    vendido_reservado = models.PositiveIntegerField(db_column="VENDIDO/RESERVADO")

    tipo_cliente = models.CharField(db_column="Tipo cliente", max_length=1024)
    identificador_cliente = models.CharField(db_column="Identificador cliente", max_length=1024)
    razon_social_cliente = models.CharField(db_column="Razon social cliente", max_length=1024)
    cliente_name = models.CharField(db_column="Nombre cliente", max_length=1024)
    telefono = models.CharField(db_column="Telefono", max_length=1024)
    telefono_fijo = models.CharField(db_column="Telefono fijo", max_length=1024)
    email = models.CharField(db_column="Email", max_length=1024)
    codigo_postal = models.CharField(db_column="Codigo postal", max_length=1024)
    direccion_cliente = models.CharField(db_column="Direccion cliente", max_length=1024)
    direccion_cliente2 = models.CharField(db_column="Direccion cliente 2", max_length=1024)

    localidad = models.CharField(db_column="Localidad", max_length=1024)
    provincia = models.CharField(db_column="Provincia", max_length=1024)

    vehiculo_demanda_marca = models.CharField(db_column="Vehiculo demandado Marca", max_length=1024)
    vehiculo_demanda_modelo = models.CharField(db_column="Vehiculo demandado Modelo", max_length=1024)
    vehiculo_demanda_modelo_precio = models.CharField(db_column="Vehiculo demandado precio", max_length=1024)
    vehiculo_demanda_kilometro = models.CharField(db_column="Vehiculo demandado kilometro", max_length=1024)
    vehiculo_demanda_anio = models.PositiveIntegerField(db_column="Vehiculo demandado anio")
    vehiculo_demanda_combustible = models.CharField(db_column="Vehiculo demandado combustible", max_length=1024)
    vehiculo_demanda_tipo = models.CharField(db_column="Vehiculo demandado tipo", max_length=1024)
    vehiculo_demanda_categoria_comercial = models.CharField(db_column="Vehiculo demandado categoria comercial", max_length=1024)
    vehiculo_demanda_potencia = models.CharField(db_column="Vehiculo demandado potencia", max_length=1024)
    vehiculo_demanda_caja_cambios = models.CharField(db_column="Vehiculo demandado tipo caja cambios", max_length=1024)
    vehiculo_demanda_anuncio = models.CharField(db_column="Vehiculo demandado link anuncio", max_length=1024)

    marca_vehiculo_actual = models.CharField(db_column="Marca vehiculo actual", max_length=1024)
    modelo_vehiculo_actual = models.CharField(db_column="Modelo vehiculo actual", max_length=1024)
    version_vehiculo_actual = models.CharField(db_column="Version vehiculo actual", max_length=1024)
    km_vehiculo_actual = models.CharField(db_column="Kilometros vehiculo actual", max_length=1024)
    estado_vehiculo_actual = models.CharField(db_column="Estado vehiculo actual", max_length=1024)
    acabado_vehiculo_actual = models.CharField(db_column="Acabados vehiculo actual", max_length=1024)
    precio_vo_vehiculo_actual = models.CharField(db_column="Precio evaluacion VO vehiculo actual", max_length=1024)
    vehiculos_flota_actual = models.CharField(db_column="Numero vehiculos total flota", max_length=1024)
    vehiculos_comerciales_flota_actual = models.CharField(db_column="Numero vehiculos comerciales flota", max_length=1024)
    vehiculos_turismos_flota_actual = models.CharField(db_column="Numero vehiculos turismos flota", max_length=1024)
    nota_flota = models.CharField(db_column="Notas flota", max_length=1024)
    matricula_vehiculo_actual = models.CharField(db_column="Matricula vehiculo actual", max_length=1024)
    fecha_compra_vehiculo_actual = models.CharField(db_column="Fecha compra vehiculo actual", max_length=1024)
    fecha_matriculacion_vehiculo_actual = models.CharField(db_column="Fecha matriculacion vehiculo actual", max_length=1024)
    fecha_ultimo_taller_vehiculo_actual = models.CharField(db_column="Fecha ultimo taller vehiculo actual", max_length=1024)
    caballos_vehiculo_actual = models.CharField(db_column="Caballos vehiculo actual", max_length=1024)
    es_financiado_vehiculo_actual = models.CharField(db_column="Vehiculo actual es financiado", max_length=1024)

    notas = models.CharField(db_column="Notas", max_length=1024)
    probabilidad_de_compra = models.CharField(db_column="Probabilidad de compra", max_length=1024)
    resultado_historico = models.CharField(db_column="Resultado historico", max_length=1024)
    reactivado = models.BooleanField(db_column="Reactivado")
    lead_recibido = models.PositiveIntegerField(db_column="LEAD RECIBIDO")
    fecha_de_alta = models.CharField(db_column="Fecha de alta", max_length=1024)
    lead_util = models.PositiveIntegerField(db_column="LEAD UTIL")
    cerrados = models.PositiveIntegerField(db_column="CERRADOS")
    disponible = models.PositiveIntegerField(db_column="Disponible")

    tareas_pendientes = models.PositiveIntegerField(db_column="Tareas pendientes")
    fecha_llamada_saliente = models.CharField(db_column="Fecha llamada saliente", max_length=1024)
    status_call = models.CharField(db_column="Status call", max_length=1024)
    fecha_email_entrante = models.CharField(db_column="Fecha email entrante", max_length=1024)
    fecha_email_saliente = models.CharField(db_column="Fecha email saliente", max_length=1024)
    fecha_lead_no_atendido = models.CharField(db_column="Fecha lead no atendido", max_length=1024)
    fecha_tareas_pendientes = models.CharField(db_column="Fecha tareas pendientes", max_length=1024)
    fecha_lead_atendido = models.CharField(db_column="Fecha lead atendido", max_length=1024)
    fecha_lead_en_seguimiento = models.CharField(db_column="Fecha lead en seguimiento", max_length=1024)
    fecha_cierre_lead = models.CharField(db_column="Fecha cierre lead", max_length=1024)
    fecha_reactivacion_lead = models.CharField(db_column="Fecha reactivacion lead", max_length=1024)
    tumbral_concesion_llamadas = models.DecimalField(db_column="TUmbral concesion llamadas", max_digits=17, decimal_places=4)
    tumbral_concesion_email = models.DecimalField(db_column="TUmbral concesion email", max_digits=17, decimal_places=4)
    asa_llamadas = models.DecimalField(db_column="ASA LLAMADAS", max_digits=17, decimal_places=4)
    asa_email = models.DecimalField(db_column="ASA EMAIL", max_digits=17, decimal_places=4)
    tumbral_llamada_superado = models.IntegerField(db_column="Tumbral llamada superado")
    tumbral_email_superado = models.IntegerField(db_column="Tumbral email superado")
    fecha_primera_tarea_programada = models.CharField(db_column="Fecha primera tarea programada", max_length=1024)
    fecha_ultima_tarea_programada = models.CharField(db_column="Fecha ultima tarea programada", max_length=1024)
    fecha_primera_tarea_realizada = models.CharField(db_column="Fecha primera tarea realizada", max_length=1024)
    fecha_ultima_tarea_realizada = models.CharField(db_column="Fecha ultima tarea realizada", max_length=1024)
    numero_tareas_programadas = models.IntegerField(db_column="Numero de tareas programadas")
    numero_tareas_realizadas = models.IntegerField(db_column="Numero de tareas realizadas")
    fecha_primer_seguimiento_programado = models.CharField(db_column="Fecha primer seguimiento a programado", max_length=1024)
    fecha_ultimo_seguimiento_programado = models.CharField(db_column="Fecha ultima seguimiento a programado", max_length=1024)
    numero_seguimientos_programados = models.IntegerField(db_column="Numero seguimientos programados")
    fecha_primer_seguimiento_realizado = models.CharField(db_column="Fecha primer seguimiento realizado", max_length=1024)
    fecha_ultimo_seguimiento_realizado = models.CharField(db_column="Fecha ultimo seguimiento realizado", max_length=1024)
    numero_seguimientos_realizados = models.IntegerField(db_column="Numero de seguimientos realizados")
    fecha_primera_llamada_cliente = models.CharField(db_column="Fecha primera llamada cliente realizada", max_length=1024)
    fecha_ultima_llamada_cliente = models.CharField(db_column="Fecha ultima llamada cliente realizada", max_length=1024)
    numero_llamadas_realizadas = models.IntegerField(db_column="Numero de llamadas realizadas")
    fecha_primer_emai_enviado = models.CharField(db_column="Fecha primera mail enviado", max_length=1024)
    fecha_ultimo_emai_enviado = models.CharField(db_column="Fecha ultimo mail enviado", max_length=1024)
    numero_email_enviados = models.IntegerField(db_column="Numero de mails enviados")
    fecha_primer_whatsapp = models.CharField(db_column="Primer whatsapp", max_length=1024)
    fecha_ultimo_whatsapp = models.CharField(db_column="Ultimo whatsapp", max_length=1024)
    numero_whatsapp = models.IntegerField(db_column="Numero whatsapp")

    concessionaire = models.ForeignKey(Concessionaire, null=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(db_column="created")

    class Meta:
        managed = False
        db_table = "MASTER_INFOAUTO_VIEW"


class LeadMasterPersistente(models.Model):
    id = models.PositiveIntegerField(primary_key=True, db_column="id")
    concesion_nombre = models.CharField(db_column="Nombre de la concesion", max_length=512)
    origen = models.CharField(db_column="Origen", max_length=1024)
    medio = models.CharField(db_column="Medio", max_length=1024)
    origen_publicidad = models.CharField(db_column="Origen publicidad", max_length=1024)
    exposicion = models.BooleanField(db_column="Exposicion")

    asignado = models.CharField(db_column="Asignado a", max_length=1024)
    fecha_llamada_entrante = models.CharField(db_column="Fecha llamada entrante", max_length=1024)
    estado = models.CharField(db_column="Estado", max_length=1024)
    resultado = models.CharField(db_column="Resultado", max_length=1024)
    motivo_resultado = models.CharField(db_column="Motivo resultado", max_length=1024)
    vendido_reservado = models.PositiveIntegerField(db_column="VENDIDO/RESERVADO")

    tipo_cliente = models.CharField(db_column="Tipo cliente", max_length=1024)
    identificador_cliente = models.CharField(db_column="Identificador cliente", max_length=1024)
    razon_social_cliente = models.CharField(db_column="Razon social cliente", max_length=1024)
    cliente_name = models.CharField(db_column="Nombre cliente", max_length=1024)
    telefono = models.CharField(db_column="Telefono", max_length=1024)
    telefono_fijo = models.CharField(db_column="Telefono fijo", max_length=1024)
    email = models.CharField(db_column="Email", max_length=1024)
    codigo_postal = models.CharField(db_column="Codigo postal", max_length=1024)
    direccion_cliente = models.CharField(db_column="Direccion cliente", max_length=1024)
    direccion_cliente2 = models.CharField(db_column="Direccion cliente 2", max_length=1024)

    localidad = models.CharField(db_column="Localidad", max_length=1024)
    provincia = models.CharField(db_column="Provincia", max_length=1024)

    vehiculo_demanda_marca = models.CharField(db_column="Vehiculo demandado Marca", max_length=1024)
    vehiculo_demanda_modelo = models.CharField(db_column="Vehiculo demandado Modelo", max_length=1024)
    vehiculo_demanda_modelo_precio = models.CharField(db_column="Vehiculo demandado precio", max_length=1024)
    vehiculo_demanda_kilometro = models.CharField(db_column="Vehiculo demandado kilometro", max_length=1024)
    vehiculo_demanda_anio = models.PositiveIntegerField(db_column="Vehiculo demandado anio")
    vehiculo_demanda_combustible = models.CharField(db_column="Vehiculo demandado combustible", max_length=1024)
    vehiculo_demanda_tipo = models.CharField(db_column="Vehiculo demandado tipo", max_length=1024)
    vehiculo_demanda_categoria_comercial = models.CharField(db_column="Vehiculo demandado categoria comercial", max_length=1024)
    vehiculo_demanda_potencia = models.CharField(db_column="Vehiculo demandado potencia", max_length=1024)
    vehiculo_demanda_caja_cambios = models.CharField(db_column="Vehiculo demandado tipo caja cambios", max_length=1024)
    vehiculo_demanda_anuncio = models.CharField(db_column="Vehiculo demandado link anuncio", max_length=1024)

    marca_vehiculo_actual = models.CharField(db_column="Marca vehiculo actual", max_length=1024)
    modelo_vehiculo_actual = models.CharField(db_column="Modelo vehiculo actual", max_length=1024)
    version_vehiculo_actual = models.CharField(db_column="Version vehiculo actual", max_length=1024)
    km_vehiculo_actual = models.CharField(db_column="Kilometros vehiculo actual", max_length=1024)
    estado_vehiculo_actual = models.CharField(db_column="Estado vehiculo actual", max_length=1024)
    acabado_vehiculo_actual = models.CharField(db_column="Acabados vehiculo actual", max_length=1024)
    precio_vo_vehiculo_actual = models.CharField(db_column="Precio evaluacion VO vehiculo actual", max_length=1024)
    vehiculos_flota_actual = models.CharField(db_column="Numero vehiculos total flota", max_length=1024)
    vehiculos_comerciales_flota_actual = models.CharField(db_column="Numero vehiculos comerciales flota", max_length=1024)
    vehiculos_turismos_flota_actual = models.CharField(db_column="Numero vehiculos turismos flota", max_length=1024)
    nota_flota = models.CharField(db_column="Notas flota", max_length=1024)
    matricula_vehiculo_actual = models.CharField(db_column="Matricula vehiculo actual", max_length=1024)
    fecha_compra_vehiculo_actual = models.CharField(db_column="Fecha compra vehiculo actual", max_length=1024)
    fecha_matriculacion_vehiculo_actual = models.CharField(db_column="Fecha matriculacion vehiculo actual", max_length=1024)
    fecha_ultimo_taller_vehiculo_actual = models.CharField(db_column="Fecha ultimo taller vehiculo actual", max_length=1024)
    caballos_vehiculo_actual = models.CharField(db_column="Caballos vehiculo actual", max_length=1024)
    es_financiado_vehiculo_actual = models.CharField(db_column="Vehiculo actual es financiado", max_length=1024)

    notas = models.CharField(db_column="Notas", max_length=1024)
    probabilidad_de_compra = models.CharField(db_column="Probabilidad de compra", max_length=1024)
    resultado_historico = models.CharField(db_column="Resultado historico", max_length=1024)
    reactivado = models.BooleanField(db_column="Reactivado")
    lead_recibido = models.PositiveIntegerField(db_column="LEAD RECIBIDO")
    fecha_de_alta = models.CharField(db_column="Fecha de alta", max_length=1024)
    lead_util = models.PositiveIntegerField(db_column="LEAD UTIL")
    cerrados = models.PositiveIntegerField(db_column="CERRADOS")
    disponible = models.PositiveIntegerField(db_column="Disponible")

    tareas_pendientes = models.PositiveIntegerField(db_column="Tareas pendientes")
    fecha_llamada_saliente = models.CharField(db_column="Fecha llamada saliente", max_length=1024)
    status_call = models.CharField(db_column="Status call", max_length=1024)
    fecha_email_entrante = models.CharField(db_column="Fecha email entrante", max_length=1024)
    fecha_email_saliente = models.CharField(db_column="Fecha email saliente", max_length=1024)
    fecha_lead_no_atendido = models.CharField(db_column="Fecha lead no atendido", max_length=1024)
    fecha_tareas_pendientes = models.CharField(db_column="Fecha tareas pendientes", max_length=1024)
    fecha_lead_atendido = models.CharField(db_column="Fecha lead atendido", max_length=1024)
    fecha_lead_en_seguimiento = models.CharField(db_column="Fecha lead en seguimiento", max_length=1024)
    fecha_cierre_lead = models.CharField(db_column="Fecha cierre lead", max_length=1024)
    fecha_reactivacion_lead = models.CharField(db_column="Fecha reactivacion lead", max_length=1024)
    tumbral_concesion_llamadas = models.DecimalField(db_column="TUmbral concesion llamadas", max_digits=17, decimal_places=4)
    tumbral_concesion_email = models.DecimalField(db_column="TUmbral concesion email", max_digits=17, decimal_places=4)
    asa_llamadas = models.DecimalField(db_column="ASA LLAMADAS", max_digits=17, decimal_places=4)
    asa_email = models.DecimalField(db_column="ASA EMAIL", max_digits=17, decimal_places=4)
    tumbral_llamada_superado = models.IntegerField(db_column="Tumbral llamada superado")
    tumbral_email_superado = models.IntegerField(db_column="Tumbral email superado")
    fecha_primera_tarea_programada = models.CharField(db_column="Fecha primera tarea programada", max_length=1024)
    fecha_ultima_tarea_programada = models.CharField(db_column="Fecha ultima tarea programada", max_length=1024)
    fecha_primera_tarea_realizada = models.CharField(db_column="Fecha primera tarea realizada", max_length=1024)
    fecha_ultima_tarea_realizada = models.CharField(db_column="Fecha ultima tarea realizada", max_length=1024)
    numero_tareas_programadas = models.IntegerField(db_column="Numero de tareas programadas")
    numero_tareas_realizadas = models.IntegerField(db_column="Numero de tareas realizadas")
    fecha_primer_seguimiento_programado = models.CharField(db_column="Fecha primer seguimiento a programado", max_length=1024)
    fecha_ultimo_seguimiento_programado = models.CharField(db_column="Fecha ultima seguimiento a programado", max_length=1024)
    numero_seguimientos_programados = models.IntegerField(db_column="Numero seguimientos programados")
    fecha_primer_seguimiento_realizado = models.CharField(db_column="Fecha primer seguimiento realizado", max_length=1024)
    fecha_ultimo_seguimiento_realizado = models.CharField(db_column="Fecha ultimo seguimiento realizado", max_length=1024)
    numero_seguimientos_realizados = models.IntegerField(db_column="Numero de seguimientos realizados")
    fecha_primera_llamada_cliente = models.CharField(db_column="Fecha primera llamada cliente realizada", max_length=1024)
    fecha_ultima_llamada_cliente = models.CharField(db_column="Fecha ultima llamada cliente realizada", max_length=1024)
    numero_llamadas_realizadas = models.IntegerField(db_column="Numero de llamadas realizadas")
    fecha_primer_emai_enviado = models.CharField(db_column="Fecha primera mail enviado", max_length=1024)
    fecha_ultimo_emai_enviado = models.CharField(db_column="Fecha ultimo mail enviado", max_length=1024)
    numero_email_enviados = models.IntegerField(db_column="Numero de mails enviados")
    fecha_primer_whatsapp = models.CharField(db_column="Primer whatsapp", max_length=1024)
    fecha_ultimo_whatsapp = models.CharField(db_column="Ultimo whatsapp", max_length=1024)
    numero_whatsapp = models.IntegerField(db_column="Numero whatsapp")

    concessionaire = models.ForeignKey(Concessionaire, null=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(db_column="created")

    class Meta:
        managed = False
        db_table = "MASTER_INFOAUTO_PERSISTENTE"