# Generated by Django 2.0.5 on 2018-07-06 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(help_text='Fecha y hora en la que se ha realizado la acción.', verbose_name='Fecha y hora de la operación')),
                ('system', models.CharField(default=None, help_text='Sistema del que depende la operación.', max_length=64, null=True, verbose_name='Sistema')),
                ('subsystem', models.CharField(default=None, help_text='Subsistema del que depende la operación.', max_length=64, null=True, verbose_name='Subsistema')),
                ('action', models.CharField(default=None, help_text='Acción ejecutada.', max_length=256, null=True, verbose_name='Acción')),
                ('description', models.CharField(help_text='Descripción de la acción ejecutada.', max_length=1024, verbose_name='Descripción')),
                ('url', models.TextField(help_text='Dirección URL llamada para la ejecución de la acción.', verbose_name='Dirección URL')),
                ('http_get_parameters', models.TextField(default=None, help_text='Parámetros GET recibidos por el servidor.', null=True, verbose_name='Parámetros GET')),
                ('http_post_parameters', models.TextField(default=None, help_text='Parámetros POST recibidos por el servidor.', null=True, verbose_name='Parámetros POST')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('HEAD', 'HEAD'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='get', help_text='Método HTTP.', max_length=32, verbose_name='Método HTTP')),
                ('http_user_agent', models.CharField(help_text='Agente de usuario que envía el navegador al servidor.', max_length=1024, verbose_name='Agente de usuario del cliente')),
                ('ip', models.GenericIPAddressField(help_text='Dirección IP del cliente que ejecuta esta acción.', verbose_name='Dirección IP')),
                ('extra', models.TextField(default=None, help_text='Datos extra de utilidad.', null=True, verbose_name='Datos extra')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica si esta acción ha sido realizada por personal interno', verbose_name='Acción realizada por personal de la aplicación')),
                ('response', models.TextField(default=None, help_text='Respuesta que provoca la acción', null=True, verbose_name='Respuesta de la acción')),
                ('status_code', models.CharField(default=None, help_text='Código de la respuesta', max_length=32, null=True, verbose_name='Código de la respuesta')),
                ('executor_user', models.ForeignKey(default=None, help_text='Usuario que ha realizado la operación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_actions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que ha realizado la operación')),
                ('impersonate_user', models.ForeignKey(default=None, help_text='Usuario impersonado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonated_logged_actions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario impersonado')),
            ],
            options={
                'ordering': ['-creation_datetime', 'system'],
                'permissions': (('view_all', 'Ver acciones registradas'), ('view_all_staff', 'Ver acciones registradas por los administradores')),
                'verbose_name_plural': 'acciones registradas',
                'verbose_name': 'acción registrada',
            },
        ),
        migrations.AlterIndexTogether(
            name='loggedaction',
            index_together={('executor_user', 'creation_datetime', 'system', 'subsystem', 'action'), ('executor_user', 'is_staff', 'creation_datetime', 'system', 'subsystem', 'action'), ('ip', 'creation_datetime', 'system', 'subsystem', 'action'), ('creation_datetime', 'system', 'subsystem', 'action')},
        ),
    ]
