# Generated by Django 2.1 on 2019-02-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionlogging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedaction',
            name='url',
            field=models.CharField(help_text='Dirección URL llamada para la ejecución de la acción.', max_length=1024, verbose_name='Dirección URL'),
        ),
    ]
