# Generated by Django 2.1 on 2019-11-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionlogging', '0002_auto_20190222_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loggedaction',
            options={'ordering': ['-creation_datetime', 'system'], 'verbose_name': 'acción registrada', 'verbose_name_plural': 'acciones registradas'},
        ),
    ]
