# Generated by Django 2.1 on 2019-03-29 12:44

from django.db import migrations
from django.db.migrations import RunPython


def build_default_flow_commands(apps, schema_editor):
    Flow = apps.get_model('netelip', 'Flow')
    Command = apps.get_model('netelip', 'Command')
    flow_c2c = Flow.objects.get_or_create(name="Flujo llamada saliente (Click 2 Call)",
                                          type='c2c', is_default=True)
    flow_incoming_call = Flow.objects.get_or_create(name="Flujo llamada entrante", type='flow',
                                                    is_default=True)
    msg_c2c = "google;es;Transfiriendo llamada al cliente. Espere un momento por favor."
    msg_incoming_call = "google;es;Transfiriendo llamada con el agente. Espere un momento por favor."
    for instance, msg in [(flow_c2c[0], msg_c2c), (flow_incoming_call[0], msg_incoming_call)]:
        c_0 = Command.objects.get_or_create(
            is_initial=True, flow=instance, command="speak",
            options=msg
        )[0]
        c_1 = Command.objects.get_or_create(flow=instance, command="record", options="")[0]
        c_1.prev_commands.add(c_0)
        c_1.save()
        c_2 = Command.objects.get_or_create(flow=instance, command="callerid", options="%(src)s;%(src)s")[0]
        c_2.prev_commands.add(c_1)
        c_2.save()
        c_3 = Command.objects.get_or_create(flow=instance, command="dial", options="pstn,%(called)s,60")[0]
        c_3.prev_commands.add(c_2)
        c_3.save()
        c_4 = Command.objects.get_or_create(
            flow=instance, command="speak",
            options="google;es;Ha habido un problema con el procesamiento de la llamada. "
                    "Por favor, inténtelo de nuevo mas tarde", is_error=True)[0]
        c_5 = Command.objects.get_or_create(flow=instance, command="hangup", options="")[0]
        c_5.prev_commands.add(c_3, c_4)
        c_5.save()


class Migration(migrations.Migration):

    dependencies = [
        ('netelip', '0002_auto_20190401_1619'),
    ]

    operations = [
        RunPython(build_default_flow_commands, RunPython.noop)
    ]
