# Generated by Django 2.1 on 2019-07-22 10:08

from django.db import migrations

def update_command(apps, schema_editor):
    Command = apps.get_model('netelip', 'Command')
    Flow = apps.get_model('netelip', 'Flow')

    flow = Flow.objects.get(type='flow')
    command_to_update = Command.objects.filter(command='callerid', flow=flow).first()
    command_to_update.options = "%(src)s;%(dst)s"
    command_to_update.save()


class Migration(migrations.Migration):

    dependencies = [
        ('netelip', '0005_auto_20190425_0933'),
    ]

    operations = [
        migrations.RunPython(update_command),
    ]
