# Generated by Django 2.2 on 2020-11-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netelip', '0010_auto_20200506_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcontrolmodel',
            name='ubunet_agent',
            field=models.CharField(default=None, help_text='Agente en ubunet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callcontrolmodel',
            name='ubunet_audio_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callcontrolmodel',
            name='ubunet_company',
            field=models.CharField(default=None, help_text='Company en ubunet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callcontrolmodel',
            name='ubunet_extension',
            field=models.CharField(default=None, help_text='Extension en ubunet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callcontrolmodel',
            name='ubunet_holdtime',
            field=models.IntegerField(default=None, help_text='Tiempo en espera', null=True),
        ),
        migrations.AddField(
            model_name='historicalcallcontrolmodel',
            name='ubunet_agent',
            field=models.CharField(default=None, help_text='Agente en ubunet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcallcontrolmodel',
            name='ubunet_audio_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcallcontrolmodel',
            name='ubunet_company',
            field=models.CharField(default=None, help_text='Company en ubunet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcallcontrolmodel',
            name='ubunet_extension',
            field=models.CharField(default=None, help_text='Extension en ubunet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcallcontrolmodel',
            name='ubunet_holdtime',
            field=models.IntegerField(default=None, help_text='Tiempo en espera', null=True),
        ),
    ]
