# Generated by Django 2.1 on 2019-02-06 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181024_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSessionWithHistoric',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_working', models.DateTimeField(blank=True, help_text='User starts to work', null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('end_working', models.DateTimeField(blank=True, help_text='Last time when user was working', null=True)),
                ('forced_online_status', models.BooleanField(default=True, help_text='If True, is currently working')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Session With Historic',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SessionWithHistoric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_working', models.DateTimeField(blank=True, help_text='User starts to work', null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('end_working', models.DateTimeField(blank=True, help_text='Last time when user was working', null=True)),
                ('forced_online_status', models.BooleanField(default=True, help_text='If True, is currently working')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session With Historic',
                'verbose_name_plural': 'Sessions With Historic',
            },
        ),
    ]
