# Generated by Django 2.1 on 2019-02-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190207_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='memberid',
            field=models.CharField(blank=True, help_text='Member Id for Click2Call', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='memberid',
            field=models.CharField(blank=True, help_text='Member Id for Click2Call', max_length=255, null=True),
        ),
    ]
