# Generated by Django 2.1 on 2019-03-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190214_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='id_click2call',
            field=models.CharField(blank=True, help_text='Id for Click2Call', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_click2call',
            field=models.CharField(blank=True, help_text='Id for Click2Call', max_length=255, null=True),
        ),
    ]
