# Generated by Django 2.1 on 2019-03-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190307_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsessionwithhistoric',
            name='worked_hours',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionwithhistoric',
            name='worked_hours',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
