# Generated by Django 2.1 on 2019-06-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190425_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Campo donde el usuario indica si se encuentra disponible o no para trabajar'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Campo donde el usuario indica si se encuentra disponible o no para trabajar'),
        ),
    ]
