# Generated by Django 2.1 on 2019-09-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190625_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='last_action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
