# Generated by Django 2.1 on 2020-05-06 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200213_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSFA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=224)),
                ('event', models.CharField(choices=[('lead_not_attended', 'Lead no atendido'), ('lead_attended', 'Lead atendido')], max_length=224)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='emails_received',
            field=models.BooleanField(default=False, help_text='Email recibidos'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='lost_calls',
            field=models.BooleanField(default=False, help_text='Llamadas perdidas'),
        ),
        migrations.AddField(
            model_name='user',
            name='emails_received',
            field=models.BooleanField(default=False, help_text='Email recibidos'),
        ),
        migrations.AddField(
            model_name='user',
            name='lost_calls',
            field=models.BooleanField(default=False, help_text='Llamadas perdidas'),
        ),
        migrations.AddField(
            model_name='usersfa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sfa_configurations', to=settings.AUTH_USER_MODEL),
        ),
    ]
