# Generated by Django 2.1 on 2020-05-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200506_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfa',
            name='event',
            field=models.CharField(choices=[('lead_not_attended', 'Lead no atendido'), ('lead_attended', 'Lead atendido'), ('lead_end', 'Lead finalizado'), ('lead_create_task', 'Nueva tarea creada en lead'), ('lead_done_task', 'Tarea finalizada en lead'), ('lead_create_traking', 'Nuevo seguimiento en lead'), ('lead_done_traking', 'Seguimiento finalizado en lead'), ('incoming_all', 'Llamada entrante en lead'), ('outcomming_all', 'Llamada saliente en lead')], max_length=224),
        ),
    ]
