# Generated by Django 2.1 on 2020-05-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200506_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='ddi_whatsapp_business',
            field=models.CharField(blank=True, help_text='DDis WhatsApp Business', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ddi_whatsapp_business',
            field=models.CharField(blank=True, help_text='DDis WhatsApp Business', max_length=255, null=True),
        ),
    ]
