# Generated by Django 2.0.1 on 2018-04-16 08:54

from django.db import migrations


def add_localities(apps, schema_editor):
    Locality = apps.get_model("countries", "Locality")
    Locality.objects.create(name="Santa Maria da Feira", province_id=749)
    Locality.objects.create(name="Arouca", province_id=749)


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_auto_20180314_1602'),
    ]

    operations = [
        migrations.RunPython(add_localities),
    ]
