# Generated by Django 2.1 on 2019-07-12 06:21

from django.db import migrations

def update_province_valencia(apps, schema_editor):
    Province = apps.get_model('countries', 'Province')
    valencia = Province.objects.get(id=652)
    valencia.name = "Valencia"
    valencia.save()

class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_auto_20180416_0854'),
    ]

    operations = [
        migrations.RunPython(update_province_valencia),
    ]
