# Generated by Django 2.1 on 2019-07-12 06:21

from django.db import migrations

def update_alicante(apps, schema_editor):
    Province = apps.get_model('countries', 'Province')
    valencia = Province.objects.get(id=641)
    valencia.name = "Alicante/Alacant"
    valencia.save()

class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_update_valencia_name'),
    ]

    operations = [
        migrations.RunPython(update_alicante),
    ]
