# Generated by Django 2.2 on 2020-07-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_update_alicante_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name']},
        ),
    ]
