# Generated by Django 2.2 on 2020-07-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_auto_20200723_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code_number', models.PositiveIntegerField()),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postal_codes', to='countries.Locality')),
            ],
        ),
    ]
