# Generated by Django 2.1 on 2019-04-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netelip_leads', '0002_auto_20190415_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcallcontrolleadmodel',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
