# Generated by Django 2.1 on 2019-11-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netelip_leads', '0003_auto_20190425_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcontrolleadmodel',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcallcontrolleadmodel',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
