# Generated by Django 2.2 on 2020-07-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netelip_leads', '0005_auto_20191127_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callcontrolleadmodel',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.Lead'),
        ),
    ]
