# Generated by Django 2.2 on 2020-11-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netelip_leads', '0006_auto_20200723_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callcontrolleadmodel',
            name='call_control',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='netelip.CallControlModel'),
        ),
    ]
