# Generated by Django 2.1 on 2018-10-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20181001_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='gas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.GasType'),
        ),
    ]
