# Generated by Django 2.1 on 2018-10-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20181011_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.Origin'),
        ),
        migrations.AddField(
            model_name='phone',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.Origin'),
        ),
        migrations.AlterField(
            model_name='concessionaire',
            name='emails',
            field=models.ManyToManyField(blank=True, to='leads.Email'),
        ),
    ]
