# Generated by Django 2.1 on 2018-10-24 13:12

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0009_auto_20181016_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('acd_remote_id', models.CharField(help_text='Identificador único de la llamada', max_length=255, unique=True)),
                ('orig_phone', models.CharField(help_text='Numero de teléfono desde el que se ha llamado', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('dest_phone', models.CharField(help_text='Numero de teléfono al que se ha llamado', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('acd_audio', models.FileField(blank=True, help_text='Fichero con el audio de la llamada', null=True, upload_to='')),
                ('acd_audio_link', models.CharField(blank=True, help_text='URL al fichero de la llamada', max_length=255, null=True)),
                ('answered_call', models.BooleanField(default=False, help_text='Llamada respondida')),
                ('date_contact', models.DateTimeField(blank=True, help_text='Fecha de contacto', null=True)),
                ('duration', models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Duración de la llamada', null=True)),
            ],
            options={
                'verbose_name': 'ACD',
                'verbose_name_plural': "ACD's",
            },
        ),
        migrations.CreateModel(
            name='UserConcession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_concessionaire_admin', models.BooleanField(default=False, help_text='Administrador del concesionario')),
                ('is_business_manager', models.BooleanField(default=False, help_text='Gestor del concesionario')),
            ],
            options={
                'verbose_name': 'Relación Usuario Concesionario',
                'verbose_name_plural': 'Relaciones usuario concessionario',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ddi',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='concessionaire',
            name='users',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='ddi',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='DDI',
        ),
        migrations.AddField(
            model_name='userconcession',
            name='concessionaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Concessionaire'),
        ),
        migrations.AddField(
            model_name='userconcession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acd',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.Lead'),
        ),
        migrations.AddField(
            model_name='concessionaire',
            name='user',
            field=models.ManyToManyField(blank=True, help_text='Relación entre concesionario y usuario', through='leads.UserConcession', to=settings.AUTH_USER_MODEL),
        ),
    ]
