# Generated by Django 2.1 on 2019-01-09 13:14

from django.db import migrations


def populate_planing_dates(apps, schema_editor):
    Task = apps.get_model('leads', 'Task')
    for task in Task.objects.all():
        task.planified_realization_date = task.realization_date
        task.planified_tracking_date = task.tracking_date
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_auto_20190108_1426'),
    ]

    operations = [
        migrations.RunPython(populate_planing_dates, reverse_code=migrations.RunPython.noop),
    ]
