# Generated by Django 2.1 on 2019-01-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_calendar', '0001_initial'),
        ('leads', '0017_auto_20190115_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionaire',
            name='work_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work_calendar.Week'),
        ),
        migrations.AlterUniqueTogether(
            name='concessionaire',
            unique_together={('id', 'work_calendar')},
        ),
    ]
