# Generated by Django 2.1 on 2019-06-25 11:30

from django.db import migrations, transaction
from django.db.migrations import RunPython


@transaction.non_atomic_requests
def set_lead_on_vehicle(apps, schema_editor):
    Vehicle = apps.get_model('leads', 'Vehicle')
    for vehicle in Vehicle.objects.all():
        vehicle.lead = vehicle.leads.first()
        vehicle.save()
    HistoricalVehicle = apps.get_model('leads', 'HistoricalVehicle')
    for hvehicle in HistoricalVehicle.objects.all():
        try:
            vehicle = Vehicle.objects.get(id=hvehicle.id)
            hvehicle.lead = vehicle.leads.first()
            hvehicle.save()
        except Vehicle.DoesNotExist:
            pass


@transaction.non_atomic_requests
def set_vehicle_on_lead(apps, schema_editor):
    Lead = apps.get_model('leads', 'Lead')
    for lead in Lead.objects.all():
        lead.vehicle = lead.vehicles.first()
        lead.save()
    HistoricalLead = apps.get_model('leads', 'Lead')
    for hlead in HistoricalLead.objects.all():
        try:
            lead = Lead.objects.get(id=hlead.id)
            hlead.vehicle = lead.vehicles.first()
            hlead.save()
        except Lead.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_auto_20190625_1249'),
    ]

    operations = [
        RunPython(set_lead_on_vehicle, set_vehicle_on_lead)
    ]
