# Generated by Django 2.1 on 2019-06-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_auto_20190625_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallead',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='vehicle',
        ),
    ]
