# Generated by Django 2.1 on 2019-06-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0035_auto_20190625_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='media',
            field=models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Phone', 'Phone'), ('SMS', 'SMS'), ('E-mail', 'E-mail'), ('face', 'Presencial')], default='Phone', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='media',
            field=models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Phone', 'Phone'), ('SMS', 'SMS'), ('E-mail', 'E-mail'), ('face', 'Presencial')], default='Phone', max_length=255),
        ),
    ]
