# Generated by Django 2.1 on 2019-07-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0037_auto_20190703_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalleadaction',
            name='lead_status_planing',
            field=models.CharField(choices=[('new', 'Nuevo'), ('commercial_management', 'Commercial management'), ('tracing', 'Tracing')], help_text='Estado esperado en la próxima actuación', max_length=255),
        ),
        migrations.AlterField(
            model_name='leadaction',
            name='lead_status_planing',
            field=models.CharField(choices=[('new', 'Nuevo'), ('commercial_management', 'Commercial management'), ('tracing', 'Tracing')], help_text='Estado esperado en la próxima actuación', max_length=255),
        ),
    ]
