# Generated by Django 2.1 on 2019-11-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0043_auto_20191112_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='computed_call_asa',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='computed_email_asa',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='incoming_call_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='incoming_email_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='outgoing_call_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='outgoing_email_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='status_attended_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='status_call',
            field=models.CharField(blank=True, choices=[('attended', 'Atendida'), ('not_attended', 'No atendida'), ('out_of_working_hours', 'Fuera de horario laboral')], max_length=224, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='status_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='status_new_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='status_pending_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='status_tracing_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='computed_call_asa',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='computed_email_asa',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='incoming_call_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='incoming_email_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='outgoing_call_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='outgoing_email_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_attended_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_call',
            field=models.CharField(blank=True, choices=[('attended', 'Atendida'), ('not_attended', 'No atendida'), ('out_of_working_hours', 'Fuera de horario laboral')], max_length=224, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_new_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_pending_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status_tracing_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
