# Generated by Django 2.1 on 2019-11-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0046_auto_20191125_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='threshold_concession_call',
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='threshold_concession_email',
            field=models.PositiveIntegerField(default=7200),
        ),
        migrations.AddField(
            model_name='lead',
            name='threshold_concession_call',
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='lead',
            name='threshold_concession_email',
            field=models.PositiveIntegerField(default=7200),
        ),
    ]
