# Generated by Django 2.1 on 2019-11-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0048_manual_update_lead_bi_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalleadaction',
            name='lead_status_planing',
            field=models.CharField(choices=[('new', 'Nuevo'), ('commercial_management', 'Commercial management'), ('tracing', 'Tracing'), ('attended', 'Attended')], help_text='Estado esperado en la próxima actuación', max_length=255),
        ),
        migrations.AlterField(
            model_name='leadaction',
            name='lead_status_planing',
            field=models.CharField(choices=[('new', 'Nuevo'), ('commercial_management', 'Commercial management'), ('tracing', 'Tracing'), ('attended', 'Attended')], help_text='Estado esperado en la próxima actuación', max_length=255),
        ),
    ]
