# Generated by Django 2.1 on 2020-04-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0051_auto_20200420_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='result_error',
            field=models.CharField(blank=True, choices=[('rechaza_financiacion', 'Rechaza financiación'), ('rechaza_tasacion', 'Rechaza tasación'), ('rechaza_precio', 'Rechaza precio'), ('aplaza_compra', 'Aplaza compra'), ('compra_competencia', 'Compra competencia'), ('pre-reservado', 'Pre-Reservado'), ('reservado', 'Reservado')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='result_error',
            field=models.CharField(blank=True, choices=[('rechaza_financiacion', 'Rechaza financiación'), ('rechaza_tasacion', 'Rechaza tasación'), ('rechaza_precio', 'Rechaza precio'), ('aplaza_compra', 'Aplaza compra'), ('compra_competencia', 'Compra competencia'), ('pre-reservado', 'Pre-Reservado'), ('reservado', 'Reservado')], max_length=255, null=True),
        ),
    ]
