# Generated by Django 2.1 on 2020-04-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0052_auto_20200421_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='before_reactivated_result',
            field=models.CharField(blank=True, choices=[('not_available', 'No disponible'), ('negative', 'Negative'), ('reserved_vehicle', 'Vehicle reserved'), ('unreachable', 'Unreachable'), ('wrong', 'Duplicado'), ('error', 'Error')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='result',
            field=models.CharField(blank=True, choices=[('not_available', 'No disponible'), ('negative', 'Negative'), ('reserved_vehicle', 'Vehicle reserved'), ('unreachable', 'Unreachable'), ('wrong', 'Duplicado'), ('error', 'Error')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='before_reactivated_result',
            field=models.CharField(blank=True, choices=[('not_available', 'No disponible'), ('negative', 'Negative'), ('reserved_vehicle', 'Vehicle reserved'), ('unreachable', 'Unreachable'), ('wrong', 'Duplicado'), ('error', 'Error')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='result',
            field=models.CharField(blank=True, choices=[('not_available', 'No disponible'), ('negative', 'Negative'), ('reserved_vehicle', 'Vehicle reserved'), ('unreachable', 'Unreachable'), ('wrong', 'Duplicado'), ('error', 'Error')], max_length=255, null=True),
        ),
    ]
