# Generated by Django 2.1 on 2020-04-23 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0055_auto_20200423_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal Code', max_length=5, null=True, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '11111'. Up to 5 digits allowed.", regex='^\\d{5}$')]),
        ),
        migrations.AddField(
            model_name='client',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal Code', max_length=5, null=True, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '11111'. Up to 5 digits allowed.", regex='^\\d{5}$')]),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
