# Generated by Django 2.1 on 2020-04-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0057_auto_20200424_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='is_traking_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_traking_task',
            field=models.BooleanField(default=False),
        ),
    ]
