# Generated by Django 2.1 on 2020-05-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0063_leadmanagement_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='lead',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leads.Lead'),
        ),
        migrations.AddField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.Lead'),
        ),
    ]
