# Generated by Django 2.2 on 2020-06-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0067_remove_leadmanagement_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Fecha')),
                ('type', models.CharField(help_text='Tipo de evento en calendario', max_length=255)),
                ('subtype', models.CharField(help_text='Tipo de tarea en calendario', max_length=255)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
