# Generated by Django 2.2 on 2020-06-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0068_leadcalendar'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leadcalendar',
            table='lead_calendar_view',
        ),
    ]
