# Generated by Django 2.2 on 2020-07-02 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0069_auto_20200602_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='business_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('private', 'Particular'), ('freelance', 'Autononomo'), ('company', 'Empresa')], default='private', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='desk_phone',
            field=models.CharField(blank=True, help_text='Phone2', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='client',
            name='identification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='business_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='client_type',
            field=models.CharField(choices=[('private', 'Particular'), ('freelance', 'Autononomo'), ('company', 'Empresa')], default='private', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='desk_phone',
            field=models.CharField(blank=True, help_text='Phone2', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='identification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
