# Generated by Django 2.2 on 2020-07-02 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0071_auto_20200702_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal',
            old_name='brand_model',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='gas',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='year',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='circulation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='evaluation_vo_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='features',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='fleet_notes',
            field=models.TextField(default=' - '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appraisal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='leads.Lead'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='total_comercial_vehicles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='total_tourism_vehicles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='total_vehicles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
