# Generated by Django 2.2 on 2020-07-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0072_auto_20200702_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='fleet_notes',
            field=models.TextField(blank=True),
        ),
    ]
