# Generated by Django 2.2 on 2020-07-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0075_auto_20200703_1218'),
        ('leads', '0070_auto_20200707_1311'),
    ]

    operations = [
    ]
