# Generated by Django 2.2 on 2020-07-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0076_merge_20200709_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.Request'),
        ),
    ]
