# Generated by Django 2.2 on 2020-07-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0077_auto_20200720_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
    ]
