# Generated by Django 2.2 on 2020-07-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0078_auto_20200720_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='fleet_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
