# Generated by Django 2.2 on 2020-07-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0079_auto_20200723_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='result_comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='result_comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
