# Generated by Django 2.2 on 2020-07-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0080_auto_20200723_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='ad_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='gear_shift',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('auto', 'Auto')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ad_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gear_shift',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('auto', 'Auto')], max_length=255, null=True),
        ),
    ]
