# Generated by Django 2.2 on 2020-07-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0082_auto_20200723_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('new', 'Nuevo'), ('km0', 'Km0'), ('seminew', 'Seminuevo'), ('used', 'Ocasión')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('new', 'Nuevo'), ('km0', 'Km0'), ('seminew', 'Seminuevo'), ('used', 'Ocasión')], max_length=255, null=True),
        ),
    ]
