# Generated by Django 2.2 on 2020-08-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0085_auto_20200729_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadMaster',
            fields=[
                ('id', models.PositiveIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('duplicado', models.PositiveIntegerField(db_column='duplicado')),
                ('concesion_nombre', models.CharField(db_column='Nombre de la concesion', max_length=512)),
                ('origen', models.CharField(db_column='Origen', max_length=1024)),
                ('medio', models.CharField(db_column='Medio', max_length=1024)),
                ('telefono', models.CharField(db_column='Telefono', max_length=1024)),
                ('asignado', models.CharField(db_column='Asignado a', max_length=1024)),
                ('fecha_llamada_entrante', models.CharField(db_column='Fecha llamada entrante', max_length=1024)),
                ('estado', models.CharField(db_column='Estado', max_length=1024)),
                ('resultado', models.CharField(db_column='Resultado', max_length=1024)),
                ('cliente_name', models.CharField(db_column='Nombre del cliente', max_length=1024)),
                ('provincia', models.CharField(db_column='Provincia', max_length=1024)),
                ('vehiculo_demanda_modelo_marca', models.CharField(db_column='Vehiculo demandada modelo marca', max_length=1024)),
                ('vehiculo_demanda_modelo_precio', models.CharField(db_column='Vehiculo demandado precio', max_length=1024)),
                ('vehiculo_demanda_kilometro', models.CharField(db_column='Vehiculo demandado kilometro', max_length=1024)),
                ('vehiculo_demanda_anio', models.PositiveIntegerField(db_column='Vehiculo demandado anio')),
                ('vehiculo_demanda_combustible', models.CharField(db_column='Vehiculo demandado combustible', max_length=1024)),
                ('notas', models.CharField(db_column='Notas', max_length=1024)),
                ('probabilidad_de_compra', models.CharField(db_column='Probabilidad de compra', max_length=1024)),
                ('resultado_historico', models.CharField(db_column='Resultado historico', max_length=1024)),
                ('reactivado', models.BooleanField(db_column='Reactivado')),
                ('lead_recibido', models.PositiveIntegerField(db_column='LEAD RECIBIDO')),
                ('fecha_de_alta', models.CharField(db_column='Fecha de alta', max_length=1024)),
                ('lead_util', models.PositiveIntegerField(db_column='LEAD UTIL')),
                ('cerrados', models.PositiveIntegerField(db_column='CERRADOS')),
                ('disponible', models.PositiveIntegerField(db_column='Disponible')),
                ('vendido_reservado', models.PositiveIntegerField(db_column='VENDIDO/RESERVADO')),
                ('tareas_pendientes', models.PositiveIntegerField(db_column='Tareas pendientes')),
                ('fecha_llamada_saliente', models.CharField(db_column='Fecha llamada saliente', max_length=1024)),
                ('status_call', models.CharField(db_column='Status call', max_length=1024)),
                ('fecha_email_entrante', models.CharField(db_column='Fecha email entrante', max_length=1024)),
                ('fecha_email_saliente', models.CharField(db_column='Fecha email saliente', max_length=1024)),
                ('fecha_lead_no_atendido', models.CharField(db_column='Fecha lead no atendido', max_length=1024)),
                ('fecha_tareas_pendientes', models.CharField(db_column='Fecha tareas pendientes', max_length=1024)),
                ('fecha_lead_atendido', models.CharField(db_column='Fecha lead atendido', max_length=1024)),
                ('fecha_lead_en_seguimiento', models.CharField(db_column='Fecha lead en seguimiento', max_length=1024)),
                ('fecha_cierre_lead', models.CharField(db_column='Fecha cierre lead', max_length=1024)),
                ('fecha_reactivacion_lead', models.CharField(db_column='Fecha reactivacion lead', max_length=1024)),
                ('tumbral_concesion_llamadas', models.DecimalField(db_column='TUmbral concesion llamadas', decimal_places=4, max_digits=17)),
                ('tumbral_concesion_email', models.DecimalField(db_column='TUmbral concesion email', decimal_places=4, max_digits=17)),
                ('asa_llamadas', models.DecimalField(db_column='ASA LLAMADAS', decimal_places=4, max_digits=17)),
                ('asa_email', models.DecimalField(db_column='ASA EMAIL', decimal_places=4, max_digits=17)),
                ('tumbral_llamada_superado', models.IntegerField(db_column='Tumbral llamada superado')),
                ('tumbral_email_superado', models.IntegerField(db_column='Tumbral email superado')),
                ('lead_es_duplicado', models.IntegerField(db_column='Lead es duplicado')),
                ('identificador_interno_llamada', models.IntegerField(db_column='Identificador interno llamada')),
                ('identificador_netelip_de_llamada', models.FloatField(db_column='Identificador netelip de llamada')),
                ('created', models.DateTimeField(db_column='created')),
            ],
            options={
                'db_table': 'MASTER_INFOAUTO_VIEW',
                'managed': False,
            },
        ),
    ]
