# Generated by Django 2.2 on 2020-08-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0091_vehicleversion_size'),
        ('leads', '0087_auto_20200818_1250'),
    ]

    operations = [
    ]
