# Generated by Django 2.2 on 2020-09-04 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0099_leadwhatsappmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadwhatsappmessage',
            name='lead',
            field=models.ForeignKey(help_text='Lead', on_delete=django.db.models.deletion.CASCADE, related_name='whatsappmessage', to='leads.Lead'),
        ),
    ]
