# Generated by Django 2.2 on 2020-11-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0106_auto_20201120_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='type',
            field=models.CharField(choices=[('date', 'Visita / Test Drive'), ('appraisal', 'Appraisal'), ('budget', 'Budget'), ('bono', 'Bono pedido'), ('insurance', 'Cotizar seguro'), ('financing', 'Financing'), ('service_contract', 'Contrato servicio'), ('vehicle_information', 'Información vehículo'), ('send_catalog', 'Enviar catalogo'), ('lost_call', 'Atender una llamada perdida'), ('pre-delivery', 'Pre entrega vehículo'), ('delivery', 'Entrega vehículo'), ('campaign_mkt', 'Campaña MKT'), ('renting', 'Renting'), ('leasing', 'Leasing'), ('ofert', 'Oferta'), ('program', 'Programada'), ('vehicle_arrival', 'Llegada vehiculo'), ('campaign_mkt_tracing', 'Seguimiento Campaña MKT'), ('contact_7', 'Contacto 7 días'), ('contact_60', 'Contacto 60 días'), ('eqc_result', 'Resultado EQC'), ('other', 'Otros'), ('warranty', 'Warranty'), ('other', 'Otros'), ('response_information_mail', 'Respuesta a solicitud vía Email'), ('pending_assignment', 'Pendiente de asignación'), ('send_email', 'Enviar email'), ('workshop_appointment', 'Cita para taller')], max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('date', 'Visita / Test Drive'), ('appraisal', 'Appraisal'), ('budget', 'Budget'), ('bono', 'Bono pedido'), ('insurance', 'Cotizar seguro'), ('financing', 'Financing'), ('service_contract', 'Contrato servicio'), ('vehicle_information', 'Información vehículo'), ('send_catalog', 'Enviar catalogo'), ('lost_call', 'Atender una llamada perdida'), ('pre-delivery', 'Pre entrega vehículo'), ('delivery', 'Entrega vehículo'), ('campaign_mkt', 'Campaña MKT'), ('renting', 'Renting'), ('leasing', 'Leasing'), ('ofert', 'Oferta'), ('program', 'Programada'), ('vehicle_arrival', 'Llegada vehiculo'), ('campaign_mkt_tracing', 'Seguimiento Campaña MKT'), ('contact_7', 'Contacto 7 días'), ('contact_60', 'Contacto 60 días'), ('eqc_result', 'Resultado EQC'), ('other', 'Otros'), ('warranty', 'Warranty'), ('other', 'Otros'), ('response_information_mail', 'Respuesta a solicitud vía Email'), ('pending_assignment', 'Pendiente de asignación'), ('send_email', 'Enviar email'), ('workshop_appointment', 'Cita para taller')], max_length=255),
        ),
    ]
