# Generated by Django 2.2 on 2021-01-21 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0109_auto_20210121_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconcession',
            name='concessionaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userconcession', to='leads.Concessionaire'),
        ),
    ]
