# Generated by Django 2.2 on 2022-03-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0115_auto_20220316_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='expenses',
            field=models.ManyToManyField(blank=True, to='leads.Expense'),
        ),
    ]
