# Generated by Django 2.2 on 2022-03-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0116_auto_20220316_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='user',
        ),
    ]
