# Generated by Django 2.2 on 2022-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0118_auto_20220316_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='model',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='version',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
