# Generated by Django 2.2 on 2022-03-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0121_auto_20220317_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='b_id',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='communicationType',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='concession_id',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='m_id',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='o_id',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='s_id',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='status',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='url',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='v_id',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='investment',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='note',
        ),
        migrations.AddField(
            model_name='campaign',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
