# Generated by Django 2.2 on 2022-03-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0124_auto_20220317_0603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaignType',
            field=models.CharField(choices=[('type1', 'Tipo de Comunicación #1'), ('type2', 'Tipo de Comunicación #2'), ('type3', 'Tipo de Comunicación #3')], max_length=255, null=True),
        ),
    ]
