# Generated by Django 2.2 on 2022-03-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0131_campaign_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleversion',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'Manual'), ('MANUAL', 'Manual'), ('automatic', 'Automatico'), ('AUTOMATIC', 'Automatico')], max_length=64),
        ),
    ]
