# Generated by Django 2.2 on 2022-03-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0132_auto_20220317_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='utm_campaing',
            new_name='utm_campaign',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='lead',
        ),
        migrations.AddField(
            model_name='campaign',
            name='utm_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
