# Generated by Django 2.2 on 2022-04-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0138_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='lead',
        ),
        migrations.AddField(
            model_name='lead',
            name='comments',
            field=models.ManyToManyField(blank=True, to='leads.Comment'),
        ),
    ]
