# Generated by Django 2.2 on 2020-07-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200506_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='unavailable_reason',
            field=models.CharField(blank=True, default='', choices=[('asisting_clients', 'Atendiendo clientes'), ('breakfast', 'Desayunando'), ('bathroom', 'En el aseo'), ('excused', 'Ausencia justificada')], help_text='Motivo trabajador no se encuentra disponible', max_length=512),
        ),
        migrations.AddField(
            model_name='user',
            name='unavailable_reason',
            field=models.CharField(blank=True, default='', choices=[('asisting_clients', 'Atendiendo clientes'), ('breakfast', 'Desayunando'), ('bathroom', 'En el aseo'), ('excused', 'Ausencia justificada')], help_text='Motivo trabajador no se encuentra disponible', max_length=512),
        ),
    ]
