# Generated by Django 2.2 on 2020-11-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201120_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='ubunet_agent',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Agente en Ubunet', max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ubunet_agent',
            field=models.CharField(blank=True, default=None, help_text='Agente en Ubunet', max_length=17, null=True, unique=True),
        ),
    ]
