# Generated by Django 2.2 on 2021-07-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_userwhatsapptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwhatsapptemplate',
            name='alias',
            field=models.CharField(default='Plantilla sin nombre', max_length=224),
        ),
    ]
