# Generated by Django 2.1 on 2019-03-20 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallControlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id_call', models.FloatField(help_text='ID único de la llamada', unique=True)),
                ('api', models.CharField(help_text='Nombre del API destino de la llamada', max_length=255)),
                ('src', models.CharField(help_text='Número de origen de la llamada', max_length=255)),
                ('dst', models.CharField(help_text='Número de destino de la llamada', max_length=255)),
                ('startcall', models.DateTimeField(help_text='Fecha y hora en la que comenzó la llamada')),
                ('durationcall', models.DurationField(blank=True, help_text='Duración actual de la llamada', null=True)),
                ('durationcallanswered', models.DurationField(blank=True, help_text='Duración de la llamada una vez atendida por un agente', null=True)),
                ('command', models.CharField(blank=True, help_text='Comando ejecutado', max_length=255, null=True)),
                ('options', models.TextField(blank=True, help_text='Opciones del comando ejecutado', null=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del resultado de la ejecución del comando', null=True)),
                ('dtmf', models.CharField(blank=True, help_text='Dígito DTMF - Dígito marcado en la llamada para establecer flujo', max_length=255, null=True)),
                ('statuscode', models.IntegerField(blank=True, help_text='Código de estado de la ejecución', null=True)),
                ('statuscall', models.CharField(blank=True, choices=[('CHANUNAVAIL', 'El número llamado no existe'), ('BUSY', 'El número llamado está ocupado'), ('NOANSWER', 'El número llamado no contesta'), ('ANSWER', 'El número llamado ha contestado'), ('CANCEL', 'El número llamado ha colgado'), ('CONGESTION', 'Fallo en red telefónica por congestión'), ('UNKNOW', 'Fallo en red telefónica desconocido')], help_text='Estado de la llamada', max_length=255, null=True)),
                ('userdata', models.CharField(blank=True, help_text='Variable establecida por el usuario', max_length=255, null=True)),
                ('typesrc', models.CharField(blank=True, choices=[('ext', 'llamada con origen una extensión de tu vPBX cuando ésta tiene el asociado el "Plan de marcado de API Voice"'), ('did', 'llamada con destino un número de teléfono de netelip gestionado por API Voice')], help_text='Tipo de origen', max_length=255, null=True)),
                ('usersrc', models.CharField(blank=True, help_text="Usuario del origen de la llamada. Cuando el tipo de origen es 'ext', el valor de 'usersrc' será el usuario SIP de la extensión que realiza la llamada;Cuando el tipo de origen es 'did', será el número de teléfono de origen de la llamada, tendrá el mismo valor que 'src'.", max_length=255, null=True)),
                ('call_origin', models.CharField(blank=True, choices=[('user', 'Usuario'), ('client', 'Client')], help_text='Origen de la llamada', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'API Voice model',
                'verbose_name_plural': 'API Voice models',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCallControlModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id_call', models.FloatField(db_index=True, help_text='ID único de la llamada')),
                ('api', models.CharField(help_text='Nombre del API destino de la llamada', max_length=255)),
                ('src', models.CharField(help_text='Número de origen de la llamada', max_length=255)),
                ('dst', models.CharField(help_text='Número de destino de la llamada', max_length=255)),
                ('startcall', models.DateTimeField(help_text='Fecha y hora en la que comenzó la llamada')),
                ('durationcall', models.DurationField(blank=True, help_text='Duración actual de la llamada', null=True)),
                ('durationcallanswered', models.DurationField(blank=True, help_text='Duración de la llamada una vez atendida por un agente', null=True)),
                ('command', models.CharField(blank=True, help_text='Comando ejecutado', max_length=255, null=True)),
                ('options', models.TextField(blank=True, help_text='Opciones del comando ejecutado', null=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del resultado de la ejecución del comando', null=True)),
                ('dtmf', models.CharField(blank=True, help_text='Dígito DTMF - Dígito marcado en la llamada para establecer flujo', max_length=255, null=True)),
                ('statuscode', models.IntegerField(blank=True, help_text='Código de estado de la ejecución', null=True)),
                ('statuscall', models.CharField(blank=True, choices=[('CHANUNAVAIL', 'El número llamado no existe'), ('BUSY', 'El número llamado está ocupado'), ('NOANSWER', 'El número llamado no contesta'), ('ANSWER', 'El número llamado ha contestado'), ('CANCEL', 'El número llamado ha colgado'), ('CONGESTION', 'Fallo en red telefónica por congestión'), ('UNKNOW', 'Fallo en red telefónica desconocido')], help_text='Estado de la llamada', max_length=255, null=True)),
                ('userdata', models.CharField(blank=True, help_text='Variable establecida por el usuario', max_length=255, null=True)),
                ('typesrc', models.CharField(blank=True, choices=[('ext', 'llamada con origen una extensión de tu vPBX cuando ésta tiene el asociado el "Plan de marcado de API Voice"'), ('did', 'llamada con destino un número de teléfono de netelip gestionado por API Voice')], help_text='Tipo de origen', max_length=255, null=True)),
                ('usersrc', models.CharField(blank=True, help_text="Usuario del origen de la llamada. Cuando el tipo de origen es 'ext', el valor de 'usersrc' será el usuario SIP de la extensión que realiza la llamada;Cuando el tipo de origen es 'did', será el número de teléfono de origen de la llamada, tendrá el mismo valor que 'src'.", max_length=255, null=True)),
                ('call_origin', models.CharField(blank=True, choices=[('user', 'Usuario'), ('client', 'Client')], help_text='Origen de la llamada', max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical API Voice model',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
