# Generated by Django 2.1 on 2019-04-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netelip', '0003_default_flow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callcontrolmodel',
            options={'verbose_name': 'Llamada entrante/saliente', 'verbose_name_plural': 'Llamadas entrantes/salientes'},
        ),
        migrations.AlterModelOptions(
            name='historicalcallcontrolmodel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Llamada entrante/saliente'},
        ),
    ]
