# Generated by Django 2.1 on 2019-04-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netelip', '0004_auto_20190416_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcallcontrolmodel',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
