# Generated by Django 2.1 on 2019-11-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netelip', '0006_auto_20190722_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcontrolmodel',
            name='startcall_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcallcontrolmodel',
            name='startcall_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
