# Generated by Django 2.1 on 2020-01-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netelip', '0007_auto_20191125_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcontrolmodel',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcallcontrolmodel',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
