# Generated by Django 2.1 on 2020-05-05 17:39

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('netelip', '0008_auto_20200108_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id_sms', models.CharField(max_length=255)),
                ('from_sms', models.CharField(max_length=255)),
                ('destination_sms', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
