# Generated by Django 2.1 on 2020-05-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netelip', '0009_smsmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessages',
            name='message',
            field=models.TextField(),
        ),
    ]
