# Generated by Django 2.2 on 2020-11-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netelip', '0011_auto_20201125_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callcontrolmodel',
            name='ubunet_holdtime',
            field=models.DurationField(default=None, help_text='Duración en espera', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcallcontrolmodel',
            name='ubunet_holdtime',
            field=models.DurationField(default=None, help_text='Duración en espera', null=True),
        ),
    ]
