# Generated by Django 2.1 on 2019-02-27 12:47
import os

from django.db import migrations
from django.db.migrations import RunSQL


def manage_view(sql_file_name):
    app_path = os.path.join(os.path.dirname(__file__), sql_file_name)
    file = open(app_path, 'r')
    sql_txt = file.read()
    file.close()
    return sql_txt


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        #RunSQL(manage_view('create_views.sql'), manage_view('drop_views.sql'))
    ]
