# Generated by Django 2.1 on 2019-04-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltag',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
