# Generated by Django 2.1 on 2019-06-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_app', '0002_auto_20190425_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltag',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
