# Generated by Django 2.1 on 2019-11-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netelip_leads', '0004_auto_20191127_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callcontrolleadmodel',
            old_name='is_duplicate',
            new_name='is_duplicated',
        ),
        migrations.RenameField(
            model_name='historicalcallcontrolleadmodel',
            old_name='is_duplicate',
            new_name='is_duplicated',
        ),
    ]
